url: "http://embedded.guide"
baseurl: ""

title: Writing an Embedded OS (a work in progress)

description: An exploration of writing a tiny OS for an ARM microcontroller

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "https://pbs.twimg.com/profile_images/568418230998687744/ee0q0lQ6_400x400.jpeg"

# List of links in the navigation bar
navbar-links:
    Home: ""

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
    name: Dan Ellis
    email: dan@danellis.me
    facebook: danellis
    github: danellis
    twitter: danellis
    linkedin: in/dellis
    stackoverflow: 

# Select which links to show in the footer
footer-links-active:
    rss: true
    facebook: false
    email: true
    twitter: true
    github: true
    linkedin: true
    stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: embedded.guide

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/NewYork"
markdown: redcarpet
highlighter: pygments
permalink: /:categories/:title
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md
